version: "3.0"
services:
  web:
    build: ./forecase_app
    ports:
      - "8000:8000"
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./forecase_app/:/usr/src/app/
    env_file:
      - ./.env.dev
    depends_on:
      - db
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - "POSTGRES_USER=forecast_user"
      - "POSTGRES_PASSWORD=postgres"
      - "POSTGRES_DB=forecast"
      - "POSTGRES_HOST_AUTH_METHOD=trust"

volumes:
  postgres_data: