# Generated by Django 4.1.1 on 2022-09-22 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecast_core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forecastmodel',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
